### ISSUE TITLE
Lab 2 Final Code Cleanup Checklist:

### ISSUE THREAD

**Issue by Kujawadl** [Kujawadl/CSC_341_OS_Lab#23]
- [x] Every file has the following header comment:

```
/*
 * [Filename]
 * 
 * Baker, Ballard, Jager-Kujawa
 * CSC 341.001
 * Spring 2016
 */
```
- [x] All comments are in appropriate style (// for inline, /* */ for multiline)
- [x] All lines stay within one page width (use `\` as needed to introduce linebreaks in the code); one page width = 80 characters
- [x] Code is pretty: 
  - [x] all code is properly indented (double check! editors are often wrong!)
    - [x] all tabs have been converted to 2 spaces (saves room to avoid line wrapping when printing)
  - [x] no duplicate code
  - [x] code is easy to read (commented when meaning isn't immediately obvious)
  - [x] everything appears well-designed (avoiding use of globals unless necessary, structs/objs implemented in most efficient manner possible)
- [x] All functions in .cpp files are found in same order as corresponding .hpp files
- [x] All functions have comments describing their purpose, inputs, outputs, and/or side effects (both in .hpp _and_ .cpp files)
- [x] Files are laid out as follows: 

```
[Header comment]
[Preprocessor directives]
[Data]
[Functions]
```

**Comment by baker12** [comment]
Just got all of the emails....I can do this part at least

**Comment by Kujawadl** [comment]
Thanks Aaron,

Just remember to either make a new branch, or a new fork, and then submit
pull requests when you’re finished with any changes. It helps keep the code
a little tidier.

**Comment by baker12** [comment]
There are some of our variable settings that go over 80 columns, what do I do for that

`char const *titleFiller = "####################################################";`

is one

**Comment by Kujawadl** [comment]
Which line numbers? I’ll take a look

**Comment by baker12** [comment]
Lines 159 and 160 seem to be the only 2 so far

**Comment by Kujawadl** [comment]
See [Commit 90e81f8](https://github.com/Kujawadl/CSC_341_OS_Lab/commit/90e81f87ea9ca1411c2ca17cc96e75c9e48979a9)

You don't need to worry about pulling that commit to your local repo; it'll merge with your changes when you create your pull request. That should just serve as a template.

**Comment by baker12** [comment]
Okay those were the only 2 that were over so we should be good then

**Comment by AndrewGBallard** [comment]
Lots of code coming in on my next pull, might screw some stuff up.
