### ISSUE TITLE
Coding Standards Checklist for Lab 4

### ISSUE THREAD

**Issue by Kujawadl** [Kujawadl/CSC_341_OS_Lab#31]
- [ ] Every file has the following header comment:

```
/*
 * [Filename]
 * 
 * Baker, Ballard, Jager-Kujawa
 * CSC 341.001
 * Spring 2016
 */
```
- [ ] All comments are in appropriate style (// for inline, /* */ for multiline)
- [ ] All lines stay within one page width (use `\` as needed to introduce linebreaks in the code); one page width = 80 characters
- [ ] Code is pretty: 
  - [ ] all code is properly indented (double check! editors are often wrong!)
    - [ ] all tabs have been converted to 2 spaces (saves room to avoid line wrapping when printing)
  - [ ] no duplicate code
  - [ ] code is easy to read (commented when meaning isn't immediately obvious)
  - [ ] everything appears well-designed (avoiding use of globals unless necessary, structs/objs implemented in most efficient manner possible)
- [ ] All functions in .cpp files are found in same order as corresponding .hpp files
- [ ] All functions have comments describing their purpose, inputs, outputs, and/or side effects (both in .hpp _and_ .cpp files)
- [ ] Files are laid out as follows: 

```
[Header comment]
[Preprocessor directives]
[Data]
[Functions]
```

**Comment by AndrewGBallard** [comment]
How would you feel about making a quick object or struct called process? The data members would be something along the lines of:
- `String identifer;`
-  `PTE pageTable[];` (Obviously this can change based on how we implement pageTable.
- `registers regs`
- `int status;`

Using the statuses we already defined in OS?

**Comment by Kujawadl** [comment]
I will be looking into automated code quality checking; I believe there are several services that do this, that integrate with GitHub, and that are free for GitHub student subscribers.
